### ISSUE TITLE
Задача 1 — проверка расстановки скобок: не все требования выполнены

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#1]
Привет, спасибо за решение. 
Читаем внимательно требования к задаче — https://github.com/rarus/intern-php-developer/blob/master/task01-brackets.md

> код оформить в виде библиотеки и опубликовать на packagist.org, 

где?

> к программе должны быть написаны юнит-тесты для проверки корректности работы, использовать phpUnit, тестовые примеры придумать самостоятельно.

где?
> юнит-тесты должны запускаться через сервис travis-ci.org

где?

> в файле readme.md должен быть «зелёный» бейдж travis

где?

Выкидывай задачу в отдельный репозиторий и закрой пожалуйста требования по ней.

**Comment by mesilov** [comment]
Прошу прощения, ещё раз тогда посмотрим, где у нас остались старые хвосты.

**Comment by entodima** [comment]
Закрыл.
