### ISSUE TITLE
К обсуждению: полнота тестовых примеров

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#2]
Привет, в задаче:

> к программе должны быть написаны юнит-тесты для проверки корректности работы, использовать phpUnit, тестовые примеры придумать самостоятельно.

Твои тесты:
https://github.com/entodima/Rarus-test-1/blob/master/tests/BracketsStringScannerTest.php
Они покрывают два кейса: cкобки поставлены верно, скобки поставлены с ошибками.
Какой ещё кейс ты забыл? 
Добавлять его в код уже не нужно.

**Comment by entodima** [comment]
в строке нет скобок?

**Comment by mesilov** [comment]
да, всегда нужно проверять и граничные случаи
