### ISSUE TITLE
К обсуждению: особенности запуска тестов

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#3]
Привет, у тебя библиотека очень компактная, в файле тревиса идёт прямой вызов:

https://github.com/entodima/Rarus-test-1/blob/master/.travis.yml#L8

Как бы ты организовал запуск тестов, если бы у тебя была библиотека обширная и файлов с тестами было бы за сотню?
Правки в код уже можно не вносить, обсуждаем тут.

**Comment by entodima** [comment]
Можно было бы закинуть тесты по каталогам и вызывать в отдельном файле 'UnitTesting.php':

```
UnitTesting.php
Group1
    test1-1.php
    test1-2.php
    ...
- Group 2
    test2-1.php
    ...
...
```

**Comment by mesilov** [comment]
Всегда смотрите, как поступают ваши коллеги, можно проще и привычнее

https://github.com/Seldaek/monolog/blob/master/composer.json#L61
https://github.com/Seldaek/monolog/blob/master/phpunit.xml.dist
