### ISSUE TITLE
К обсуждению: PHP-доки для заголовков файлов

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#4]
У тебя в файле
https://github.com/entodima/Rarus-test-1/blob/master/src/BracketsStringScanner.php#L3 

Вопрос: PHP-доки ты не пишешь по идеологическим причинам или потому, что код сам себя поясняет?

Правки в файл вносить не надо, к обсуждению

**Comment by entodima** [comment]
Хотелось бы писать так, что бы код нуждался в минимуме комментов.
