### ISSUE TITLE
К обсуждению: почему не используются неймспейсы?

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#5]
Привет, у тебя твоя библиотека с функционалом проверки расстановки скобок.
Судя по файлу
https://github.com/entodima/Rarus-test-1/blob/master/src/BracketsStringScanner.php#L3

ты регистриуешь её в глобальном неймспейсе, почему?
Правки в код внорсить уже не надо, к обсуждению.

**Comment by entodima** [comment]
Протормозил. Не писал библиотеки до этого.

Допустим, если объявить класс в `namespace Entodima;`
То потом в тесте нужно было вызывать так: `Entodima\BracketsStringScanner::scan('())(');`
