### ISSUE TITLE
К обсуждению: проверка типов данных

### ISSUE THREAD

**Issue by mesilov** [entodima/Rarus-test-1#6]
Привет, у тебя в требованиях

` "php": ">=7.2"`

В коде файла https://github.com/entodima/Rarus-test-1/blob/master/src/BracketsStringScanner.php#L1 
 ты не указываешь 
`declare(strict_types=1);`

почему?

**Comment by entodima** [comment]
Не думал что тут необходима строгая типизация. Со строками же работаем.

**Comment by mesilov** [comment]
если у тебя есть возможность использовать типизацию, то ты её используешь, т.к. юзеры могут ввести мусор или любой другой тип данных
